### ISSUE TITLE
404 page not found - fresh install

### ISSUE THREAD

**Issue by noyzen** [Hope-IT-Works/WCMP#2]
Installed fresh using command you provided. everything downloaded.
Then I run caddy using command you provided (during install i used -SkipWinSW for portable setup)
And navigated to 127.0.0.1:2019 and I get "404 page not found".
I have my web files with index.html in "www" folder.

**Comment by Hope-IT-Works** [comment]
Hello @noyzen ,

thanks for trying out WCMP!

Caddy exposes a config-API on Port 2019 → [Caddy API](https://caddyserver.com/docs/api)

WCMP is configured in a way, that Caddy exposes your files on Port 443.

I just did some testing and found out, that if you want to run Caddy manually, you need to go into the Caddy directory and run Caddy from there:

```cmd
cd caddy
.\caddy run --watch
```

If you want to reach your files in `www`, you need to go to `https://127.0.0.1`.

Let me know, if you need further help.

Thank you for using WCMP.

Greeting from Berlin
@Hope-IT-Works

**Comment by noyzen** [comment]
> If you want to reach your files in `www`, you need to go to `https://127.0.0.1`.

It works now, thanks.
